import type { NextPage } from 'next'
import Head from 'next/head'


const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TELx Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page-temp">
        <h1>Guides</h1>
      </main>

    </div>
  )
}

export default Page
