import type { NextPage } from 'next'
import Head from 'next/head'
import GuideLayout from '../../components/guide/guideLayout'

import ArticleService from '../../services/article-service';
const articleService = new ArticleService();
import { ArticleProps } from "../../components/common/Article";

interface PageProps {
  articles: Array<ArticleProps>;
  welcomeArticle: ArticleProps;
}


export default function Page(props: PageProps) {
  const { articles, welcomeArticle } = props;
  const pageTitle = 'Education  |  Resources for DeFi and TELx';
  
  return (
    <div>
      <Head>
        <title>TELx Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page">
        { pageTitle && (
          <div className="page-title">
            <h1>{pageTitle}</h1>
          </div>
        )}
  
        <GuideLayout
          article={welcomeArticle}
          articles={articles}
          pageTitle={pageTitle}
        />
      </div>

    </div>
  )
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps() {
  
  const articles = await articleService.fetchAll();
  const welcomeArticle = await articleService.fetchSingle(5);
  
  return {
    props: {
      articles,
      welcomeArticle
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  }
}