import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CardPageButton from '../components/common/CardPageButton'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TELx Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <section className="home-intro-and-twitter">
          <div className="home-intro">
            <div className="home-intro-inner">
              <h1>Welcome to the Community</h1>
              <p>TELx Community is created by volunteers. We come together to bring you educational materials on DeFi and TELx. Here you will find resources to help you start your DeFi journey, as well as a family of community members supporting each other. Get started by clicking on one of the links below. If you have any questions, don’t hesitate to reach out to us on Twitter.</p>

              <div className="card-page-buttons">
                <CardPageButton 
                  linkUrl="/analytics"
                  title="Analytics"
                  icon="graph"
                  description="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros."
                />
                <CardPageButton 
                  linkUrl="/tools"
                  title="Tools"
                  icon="office-expenses"
                  description="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros."
                />
                <CardPageButton 
                  linkUrl="/guides"
                  title="Guides"
                  icon="info-circle"
                  description="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros."
                />
                <CardPageButton 
                  linkUrl="/media"
                  title="Media"
                  icon="camera"
                  description="Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros."
                />
              </div>
            </div>
          </div>
          <div className="home-twitter">
            <h4>Twitter</h4>
          </div>  
        </section>

      </main>

    </div>
  )
}

export default Home
